PREFIX base:        <http://example.com/tutorial2/vocabulary/base#>
PREFIX mission:     <http://example.com/tutorial2/vocabulary/mission#>
PREFIX components: <http://example.com/tutorial2/description/components#> 
PREFIX vim4:		<http://bipm.org/jcgm/vim4#>

INSERT DATA {
  	components:test a mission:Component ; 
  		base:hasIdentifier "testID" ;
  		base:hasCanonicalName "testName" ;
    	base:contains components:orbiter-launch-system .
}
