install.packages("reactable", repos='http://cran.us.r-project.org')
install.packages("igraph")
#install.packages("libmkl-rt")
#install.packages("libglpk40")
install.packages("networkD3")
install.packages("reticulate")
install.packages("tidyverse")
install.packages("collapsibleTree")
install.packages("colorspace")
install.packages("jsonlite")
install.packages("DT")
install.packages("devtools")
library(devtools)

install_github("UTNAK/tansakusuR")
install_github("UTNAK/omlhashiR")