PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX base: <http://example.com/tutorial2/vocabulary/base#>

select distinct ?anyIri ?id ?name
WHERE {
  BIND(<${iri}> AS ?anyIri)
  ?anyIri a owl:NamedIndividual ;
      base:hasIdentifier ?id ;
      base:hasCanonicalName ?name .
}