PREFIX vim4:	    <http://bipm.org/jcgm/vim4#>
PREFIX base:        <http://example.com/vocabulary/base#>
PREFIX mission:     <http://example.com/vocabulary/mission#>
PREFIX mechanical:  <http://example.com/vocabulary/mechanical#>

SELECT DISTINCT ?c_id (CONCAT(?c_id, " ", ?c_name) AS ?c_fullname) ?i_id  (CONCAT(?i_id, " ", ?i_name) AS ?i_fullname)

WHERE {
	?c1 a mission:Component ;
    	base:hasIdentifier ?c_id ;
    	base:hasCanonicalName ?c_name ;
		mission:presents [
			a mission:Interface ;
			base:hasIdentifier ?i_id ;
			base:hasCanonicalName ?i_name
		]
}
ORDER BY ?c_id ?i_id
