PREFIX base:        <http://example.com/vocabulary/base#>
PREFIX mission:     <http://example.com/vocabulary/mission#>
PREFIX dc:        	<http://purl.org/dc/elements/1.1/>
PREFIX operations: 	<http://example.com/vocabulary/operations#>

SELECT DISTINCT (?j_id AS ?id) (?j_name AS ?junction) (CONCAT(?i1_id, " ", ?i1_name) AS ?fromInterface) (CONCAT(?i2_id, " ", ?i2_name) AS ?toInterface)

WHERE {
	?j a mission:Junction ;
		base:hasIdentifier ?j_id ;
		base:hasCanonicalName ?j_name ;
		mission:joins1 [
			a mission:Interface ;
			base:hasIdentifier ?i1_id ;
			base:hasCanonicalName ?i1_name
		] ;
		mission:joins2 [
			a mission:Interface ;
			base:hasIdentifier ?i2_id ;
			base:hasCanonicalName ?i2_name
		]
}
ORDER BY ?j_id ?i1_id ?i2_id
