PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX base: <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX vim4: <http://bipm.org/jcgm/vim4#>
PREFIX mission: <http://imce.jpl.nasa.gov/foundation/mission#>

select distinct ?mIri ?id ?name ?mass
WHERE {
  BIND(<${iri}> AS ?mIri)
  ?mIri a owl:NamedIndividual ;
      base:hasIdentifier ?id ;
      base:hasCanonicalName ?name .
  OPTIONAL{
		?mass_placeholder vim4:characterizes ?mIri ;
			vim4:hasDoubleNumber ?mass .
    }
}