PREFIX base:        <http://example.com/vocabulary/base#>
PREFIX mission:     <http://example.com/vocabulary/mission#>

SELECT DISTINCT ?id ?name

WHERE {
	?m a mission:Mission ;
	   base:hasIdentifier ?id ;
	   base:hasCanonicalName ?name .
}
ORDER BY ?id

