PREFIX base:        <http://example.com/vocabulary/base#>
PREFIX mission:     <http://example.com/vocabulary/mission#>

SELECT DISTINCT ?obj1_id ?obj2_id

WHERE {
	?obj a mission:Objective ;
		base:hasIdentifier ?obj1_id ;
		base:aggregates [
			base:hasIdentifier ?obj2_id ;
		]
}
ORDER BY ?obj1_id
